routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

if (App::environment('production')) {
    URL::forceSchema('https');
}

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::auth();

Auth::routes();

Route::get('/', ['uses' => 'HomeController@index']);

Route::get('logout', 'Auth\LoginController@logout');

// Account
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Account', 'prefix' => 'account'], function () {
    Route::get('/', ['as' => 'account', 'uses' => 'AccountController@index']);
    Route::post('update', ['as' => 'account.update', 'uses' => 'AccountController@update']);
});

// Client
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Client', 'prefix' => 'client', 'as' => 'client.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'ClientController@index']);

    // Projects
    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'show' => 'project.show'
        ]
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    // Idea
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

    Route::resource('idea', 'IdeaController', [
        'names' => [
            'index' => 'idea',
            'create' => 'idea.create',
            'store' => 'idea.store',
            'show' => 'idea.show',
            'edit' => 'idea.edit',
            'update' => 'idea.update',
            'destroy' => 'idea.destroy'
        ]
    ]);

    //IdeaVote
    Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
});

// Admin
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access', 'internal'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Client
        Route::resource('client', 'ClientController', [
            'names' => [
                'index' => 'client',
                'create' => 'client.create',
                'store' => 'client.store',
                'show' => 'client.show',
                'edit' => 'client.edit',
                'update' => 'client.update',
                'destroy' => 'client.destroy'
            ]
        ]);
    });

    // Projects
    Route::get('project/add/{client}', ['as' => 'project.add', 'uses' => 'ProjectMilestoneController@add']);

    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'create' => 'project.create',
            'store' => 'project.store',
            'show' => 'project.show',
            'edit' => 'project.edit',
            'update' => 'project.update',
            'destroy' => 'project.destroy'
        ]
    ]);
    Route::get('project/access/{project}', ['as' => 'project.access', 'uses' => 'ProjectController@access']);
    Route::post('project/projectcode', ['as' => 'project.projectcode', 'uses' => 'ProjectController@genProjectCode']);
    Route::post('project/user/{project}', ['as' => 'project.user', 'uses' => 'ProjectController@user']);
    Route::delete('project/cancel-access/{project_user}', ['as' => 'project.cancel-access', 'uses' => 'ProjectController@cancelAccess']);

    // Project Milestones
    Route::get('project-milestone/{project}', ['as' => 'project-milestone', 'uses' => 'ProjectMilestoneController@index']);
    Route::get('project-milestone/add/{project}', ['as' => 'project-milestone.add', 'uses' => 'ProjectMilestoneController@add']);
    Route::post('project-milestone/save/{project}', ['as' => 'project-milestone.save', 'uses' => 'ProjectMilestoneController@save']);
    Route::resource('project-milestone', 'ProjectMilestoneController', [
        'names' => [
            'show' => 'project-milestone.show',
            'edit' => 'project-milestone.edit',
            'update' => 'project-milestone.update',
            'destroy' => 'project-milestone.destroy'
        ]
    ]);

    // Project Updates
    Route::get('project-update/{project}', ['as' => 'project-update', 'uses' => 'ProjectUpdateController@index']);
    Route::get('project-update/add/{project}', ['as' => 'project-update.add', 'uses' => 'ProjectUpdateController@add']);
    Route::post('project-update/save/{project}', ['as' => 'project-update.save', 'uses' => 'ProjectUpdateController@save']);
    Route::get('project-update/show/{project_update}', ['as' => 'project-update.show', 'uses' => 'ProjectUpdateController@show']);
    Route::post('project-update/comment/{project_update}', ['as' => 'project-update.comment', 'uses' => 'ProjectUpdateController@comment']);
    Route::resource('project-update', 'ProjectUpdateController', [
        'only'=>['edit', 'update', 'destroy', 'store']
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Idea
        Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

        Route::resource('idea', 'IdeaController', [
            'names' => [
                'index' => 'idea',
                'create' => 'idea.create',
                'store' => 'idea.store',
                'show' => 'idea.show',
                'edit' => 'idea.edit',
                'update' => 'idea.update',
                'destroy' => 'idea.destroy'
            ]
        ]);

        //IdeaVote
        Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
        /*
        Route::resource('ideavote', 'IdeaVoteController', [
            'names' => [
                'store' => 'ideavote.store',
                'destroy' => 'ideavote.destroy'
            ]
        ]);
        */
    });

    // Timesheet
    Route::resource('timesheet', 'TimesheetController', [
        'names' => [
            'index' => 'timesheet',
            'store' => 'timesheet.store',
            'show' => 'timesheet.show',
            'edit' => 'timesheet.edit',
            'update' => 'timesheet.update',
            'destroy' => 'timesheet.destroy'
        ]
    ]);

    //File
    Route::resource('file', 'FileController', [
        'names' => [
            'index' => 'file',
            'store' => 'file.store',
            'show' => 'file.show',
            'edit' => 'file.edit',
            'update' => 'file.update',
            'destroy' => 'file.destroy'
        ]
    ]);

    Route::get('create/{ticket?}', ['as' => 'timesheet.create', 'uses' => 'TimesheetController@create']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // User
        Route::resource('user', 'UserController', [
            'names' => [
                'index' => 'user',
                'create' => 'user.create',
                'store' => 'user.store',
                'show' => 'user.show',
                'edit' => 'user.edit',
                'update' => 'user.update',
                'destroy' => 'user.destroy'
            ]
        ]);
    });

    //Notes

    Route::get('note/create/{user}', ['as' => 'note.create', 'uses' => 'NoteController@create']);
    Route::post('note/store/{user}', ['as' => 'note.store', 'uses' => 'NoteController@store']);
    Route::get('note/edit/{note}', ['as' => 'note.edit', 'uses' => 'NoteController@edit']);
    Route::post('note/update/{note}', ['as' => 'note.update', 'uses' => 'NoteController@update']);

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content')
	<h1>Dashboard</h1>

	<div class="activityLog">
		@foreach ($incompleteMilestones as $projectMilestone)
			<div class="activity">
				<div class="activity__icon badge">
					<span class="dicon-messages"></span>
				</div>

				<div class="activity__comment">
					<div class="activity__comment--date">
						{{ \DCODESupport\Services\DisplayService::displayDate($projectMilestone->scheduled) }}<br />
						<small>{{ ($projectMilestone->scheduled > time() ? 'Ontime' : 'Overdue') }}</small>
					</div>

					<h4><a href="{{ route('admin.project.show', $projectMilestone->project_id) }}">{!! $projectMilestone->name !!}</a></h4>
					<div> ... </div>

					<div class="activity__comment--meta">
						<label>Project:</label>
						{{ \DCODESupport\Services\DisplayService::displayProject($projectMilestone->project) }}

						&nbsp;

						<label>Created By:</label>
						{{ \DCODESupport\Services\DisplayService::displayUser($projectMilestone->user) }}
					</div>
				</div>
			</div>
		@endforeach
	</div>
@endsection
{{--
@section('javascript')

	<link rel="stylesheet" href="/css/gantt.css" />
	<script src="js/jquery.fn.gantt.js"></script>
	<script type="application/javascript">
/*
        jQuery(function () {

            var data = [
                { "name": " TestName ","desc": "&rarr; TestDesc"  ,"values": [{"id": "testID", "from": "/Date(1320182000000)/", "to": "/Date(1320401600000)/", "desc": "Id: T1<br/>", "label": " test Label", "customClass": "testClass", "dep": "b4"}]},
                { "name": " TestName ","desc": "&rarr; TestDesc"  ,"values": [{"id": "testID", "from": "/Date(1320182000000)/", "to": "/Date(1320301600000)/", "desc": "Id: T1<br/>Name:   test A", "label": " test Label", "customClass": "testClass", "dep": "b4"}]},
                { "name": " Step B ","desc": "&rarr; step C"  ,"values": [{"id": "b1", "from": "/Date(1320601600000)/", "to": "/Date(1320870400000)/", "desc": "Id: 1<br/>Name:   Step B", "label": " Step B", "customClass": "ganttOrange", "dep": "b2"}]},
                { "name": " Step C ","desc": "&rarr; step D"  ,"values": [{"id": "b2", "from": "/Date(1321192000000)/", "to": "/Date(1321500400000)/", "desc": "Id: 2<br/>Name:   Step C", "label": " Step C", "customClass": "ganttGreen", "dep": "b3"}]},
                { "name": " Step D ","desc": "&rarr; step E"  ,"values": [{"id": "b3", "from": "/Date(1320302400000)/", "to": "/Date(1320551600000)/", "desc": "Id: 3<br/>Name:   Step D", "label": " Step D", "dep": "b4"}]},
                { "name": " Step E ","desc": "&mdash;"        ,"values": [{"id": "b4", "from": "/Date(1320802400000)/", "to": "/Date(1321994800000)/", "desc": "Id: 4<br/>Name:   Step E", "label": " Step E", "customClass": "ganttRed"}]},
                { "name": " Step F ","desc": "&rarr; step B"  ,"values": [{"id": "b5", "from": "/Date(1320192000000)/", "to": "/Date(1320401600000)/", "desc": "Id: 5<br/>Name:   Step F", "label": " Step F", "customClass": "ganttOrange", "dep": "b1"}]},
                { "name": " Step G ","desc": "&rarr; step C"  ,"values": [{"id": "b6", "from": "/Date(1320401600000)/", "to": "/Date(1320570400000)/", "desc": "Id: 6<br/>Name:   Step G", "label": " Step G", "customClass": "ganttGreen", "dep": "b8"}]},
                { "name": " Step H ","desc": "&rarr; Step J"  ,"values": [{"id": "b7", "from": "/Date(1321192000000)/", "to": "/Date(1321500400000)/", "desc": "Id: 7<br/>Name:   Step H", "label": " Step H", "dep": "b9"}]},
                { "name": " Step I ","desc": "&rarr; Step H"  ,"values": [{"id": "b8", "from": "/Date(1320302400000)/", "to": "/Date(1320551600000)/", "desc": "Id: 8<br/>Name:   Step I", "label": " Step I", "customClass": "ganttRed", "dep": "b7"}]},
                { "name": " Step J ","desc": "&mdash;"        ,"values": [{"id": "b9", "from": "/Date(1320802400000)/", "to": "/Date(1321994800000)/", "desc": "Id: 9<br/>Name:   Step J", "label": " Step J", "customClass": "ganttOrange"}]}
            ];

            $(".gantt").gantt({source: data, navigate: 'scroll', scale: 'days', maxScale: 'weeks', minScale: 'hours'});

        });
*/
//var render=$(".ganttData").attr('data-json');
//var renderObject=[{ 'name': ' TestName ','desc': '&rarr; TestDesc'  ,'values': [{'id': 'testID', 'from': '/Date(1320182000000)/', 'to': '/Date(1320401600000)/', 'desc': 'Id: T1<br/>', 'label': ' test Label', 'customClass': 'testClass', 'dep': 'b4'}]}];
//var milestone=$(".ganttData").attr('data-milestone');

//console.log("render: ",render);
//console.log("renderObject: ",renderObject);

// WORKING GANTT CHART
/*
        jQuery(function () {

        $(".ganttData").gantt({


                  source: $(this).attr("data-json"),
				  navigate:"scroll",
				  scale: "days",
                  minScale: "hours",
                  maxScale: "weeks",
                  onItemClick: function(data) {
                      alert("Item clicked - show some details");
                  },
                  onAddClick: function(dt, rowId) {
                      alert("Empty space clicked - add an item!");
                  },
                  onRender: function() {
                      console.log("chart rendered");
                      console.log('this.source:',this.source);
                      console.log('$(this).attr("data-json")',$(this).attr('data-json'));

                  }
              });
        });

*/

            var testing=JSON.parse($(".ganttData").attr('data-json'));
			// console.log('read from attribute:',JSON.parse(testing));

			//var myObject=testing.replaceAll("'",'"');
			//var myObject= JSON.parse(testing);
			//console.log('myObject:',myObject);

			 // var rowTesting=[{ "name": " TestName ","desc": "&rarr; TestDesc"  ,"values": [{"id": "testID", "from": "/Date(1320182000000)/", "to": "/Date(1320401600000)/", "desc": "Id: T1<br/>", "label": " test Label", "customClass": "testClass", "dep": "b4"}]}];
			// console.log('rowTesting:',rowTesting);


            $("#ganttData").gantt({
                source:testing,
				navigate: 'scroll',
				scale: 'days',
				maxScale: 'weeks',
				minScale: 'hours',
                onRender: function() {
                    console.log("chart rendered");
                    console.log(this.source);

                }
            });
	</script>
@stop
--}}

resources/views/admin/testDashboard.blade.php
@extends('layouts.admin')

@section('content')
	<h1>Dashboard</h1>

	<div class="activityLog">

		@foreach($activeProjects as $project)

			@if ($project->projectMilestones()->count() > 0)
				<div class="activity">
					<div class="activity__icon badge">
						<span class="dicon-messages"></span>
					</div>
					<div class="activity__comment">
						<div  class="activity__comment--meta">
							<label>Project:</label>
							{{ \DCODESupport\Services\DisplayService::displayProject($project) }}
							<div>
								<label>User:</label>
								{{ \DCODESupport\Services\DisplayService::displayUser($project->user) }}
							</div>
							<div> ... </div>
						</div>
						<div>
							<?php
                            	$milestone = [];
							?>
							@foreach ($project->projectMilestones as $projectMilestone)
							{{--	{!! print_r($projectMilestone) !!}	--}}
								<?php
								// Convert the time to the format that is used.
								// Resources : https://github.com/taitems/jQuery.Gantt/issues/94
									$fromTime=$projectMilestone->created_at;
									$fromTime=strtotime($fromTime);
									$fromTime=$fromTime*1000;
									$toTime=($projectMilestone->scheduled)*1000;

									$milestoneItem[]=     ["id"=> "{$projectMilestone->id} ",
										"from"=> "/Date($fromTime)/",
										"to"=> "/Date($toTime)/",
										"desc"=> "Created By:{$projectMilestone->user->first_name }<br/>",
										"label"=> " {$projectMilestone->name }",
										"customClass"=> "testClass",
										"dep"=> "{$projectMilestone->project_id}"];

										$milestone[] = [
											"name"=> " {$projectMilestone->name } ",
											//"desc"=>"&rarr; TestDesc"  ,
											"values"=> $milestoneItem
											];
										?>

                                    <?php
                                    $milestoneItem = [];// This is the exact place to clear the milestoneItem array
                                    ?>

								@endforeach
								<a class="buttonAction edit" data-href="{{ route('admin.project-milestone.add', $project->id) }}"><span>+</span></a>
								<div class="ganttData"  data-json='{!! json_encode($milestone) !!}' project-url='{!! json_encode(route('admin.project.show', $projectMilestone->project_id)) !!}' add-milestone='{!! json_encode(route('admin.project-milestone.add', $project->id)) !!}'>NO Active Milestones</div>
						</div>

					</div>
				</div>
			@endif


		@endforeach

	</div>

@endsection


@section('javascript')

	<link rel="stylesheet" href="/css/gantt.css" />
	<script src="js/jquery.fn.gantt.js"></script>
	<script type="application/javascript">
        var list = $(".ganttData").map(function(){return $(this).attr("data-json");}) ;
        console.log('List:',list);
        //console.log(list.size());

/*

        jQuery(function () {
            //console.log('BEFORE calling gantt',input);
			//$(this).attr('data-val')
            $(".ganttData").gantt({
                source:JSON.parse(list[2]),
                navigate: 'scroll',
                scale: 'days',
                maxScale: 'weeks',
                minScale: 'hours',
                onRender: function() {
                    console.log("chart rendered");
                    console.log('ON RENDER',this.source);
                    console.log($(this).attr('data-json'));

                }
            });
        });

*/
        $(".ganttData").each(function() {
            var input=JSON.parse($(this).attr('data-json'));
            var url=JSON.parse($(this).attr('project-url'));
            var addmilestone=JSON.parse($(this).attr('add-milestone'));
            console.log(addmilestone);
            console.log('Test input',input);
            $(this).gantt({
                source:input,
                navigate: 'scroll',
                scale: 'days',
                maxScale: 'weeks',
                minScale: 'hours',
                onItemClick: function(data) {
                    window.location.href = url;
		        },
                onAddClick: function(dt, rowId) {
                    //window.location.href=addmilestone;
    		    },
                onRender: function() {
                    console.log("chart rendered");
                    console.log('ON RENDER',this.source);
                    //console.log($(this).attr('data-json'));
                }
            });
        });

/*

        var list = $(".ganttData").map(function(){return $(this).attr("data-json");}) ;
       console.log('List:',list);
        //console.log(list.size());

        var i;
        for(i=0;i<list.size();i++){
			console.log('Loop:',list[i]);
			var items=list[i];
            jQuery(function () {
                var input=JSON.parse(items);
                //console.log('BEFORE calling gantt',input);
                $(".ganttData").gantt({
                    source:input,
                    navigate: 'scroll',
                    scale: 'days',
                    maxScale: 'weeks',
                    minScale: 'hours',
                    onRender: function() {
                        console.log("chart rendered");
                        console.log('ON RENDER',this.source);
                    }
                });
            });
		}

/*

/*
        $(".ganttData").each(function() {
            var input=JSON.parse($(".ganttData").attr('data-json'));
            console.log('Test input',input);
		});
*/
/*

        $(".ganttData").each(function() {

            jQuery(function () {
                var input=JSON.parse($(".ganttData").attr('data-json'));
                console.log('BEFORE calling gantt',input);
                $(".ganttData").gantt({
                    source:input,
                    navigate: 'scroll',
                    scale: 'days',
                    maxScale: 'weeks',
                    minScale: 'hours',
                    onRender: function() {
                        console.log("chart rendered");
                        console.log('ON RENDER',this.source);
                    }
                });
            });

		});
		*/
	</script>
@stop