routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

if (App::environment('production')) {
    URL::forceSchema('https');
}

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::auth();

Auth::routes();

Route::get('/', ['uses' => 'HomeController@index']);

Route::get('logout', 'Auth\LoginController@logout');

// Account
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Account', 'prefix' => 'account'], function () {
    Route::get('/', ['as' => 'account', 'uses' => 'AccountController@index']);
    Route::post('update', ['as' => 'account.update', 'uses' => 'AccountController@update']);
});

// Client
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Client', 'prefix' => 'client', 'as' => 'client.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'ClientController@index']);

    // Projects
    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'show' => 'project.show'
        ]
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    // Idea
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

    Route::resource('idea', 'IdeaController', [
        'names' => [
            'index' => 'idea',
            'create' => 'idea.create',
            'store' => 'idea.store',
            'show' => 'idea.show',
            'edit' => 'idea.edit',
            'update' => 'idea.update',
            'destroy' => 'idea.destroy'
        ]
    ]);

    //IdeaVote
    Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
});

// Admin
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access', 'internal'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Client
        Route::resource('client', 'ClientController', [
            'names' => [
                'index' => 'client',
                'create' => 'client.create',
                'store' => 'client.store',
                'show' => 'client.show',
                'edit' => 'client.edit',
                'update' => 'client.update',
                'destroy' => 'client.destroy'
            ]
        ]);
    });

    // Projects
    Route::get('project/add/{client}', ['as' => 'project.add', 'uses' => 'ProjectMilestoneController@add']);

    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'create' => 'project.create',
            'store' => 'project.store',
            'show' => 'project.show',
            'edit' => 'project.edit',
            'update' => 'project.update',
            'destroy' => 'project.destroy'
        ]
    ]);
    Route::get('project/access/{project}', ['as' => 'project.access', 'uses' => 'ProjectController@access']);
    Route::post('project/projectcode', ['as' => 'project.projectcode', 'uses' => 'ProjectController@genProjectCode']);
    Route::post('project/user/{project}', ['as' => 'project.user', 'uses' => 'ProjectController@user']);
    Route::delete('project/cancel-access/{project_user}', ['as' => 'project.cancel-access', 'uses' => 'ProjectController@cancelAccess']);

    // Project Milestones
    Route::get('project-milestone/{project}', ['as' => 'project-milestone', 'uses' => 'ProjectMilestoneController@index']);
    Route::get('project-milestone/add/{project}', ['as' => 'project-milestone.add', 'uses' => 'ProjectMilestoneController@add']);
    Route::post('project-milestone/save/{project}', ['as' => 'project-milestone.save', 'uses' => 'ProjectMilestoneController@save']);
    Route::resource('project-milestone', 'ProjectMilestoneController', [
        'names' => [
            'show' => 'project-milestone.show',
            'edit' => 'project-milestone.edit',
            'update' => 'project-milestone.update',
            'destroy' => 'project-milestone.destroy'
        ]
    ]);

    // Project Updates
    Route::get('project-update/{project}', ['as' => 'project-update', 'uses' => 'ProjectUpdateController@index']);
    Route::get('project-update/add/{project}', ['as' => 'project-update.add', 'uses' => 'ProjectUpdateController@add']);
    Route::post('project-update/save/{project}', ['as' => 'project-update.save', 'uses' => 'ProjectUpdateController@save']);
    Route::get('project-update/show/{project_update}', ['as' => 'project-update.show', 'uses' => 'ProjectUpdateController@show']);
    Route::post('project-update/comment/{project_update}', ['as' => 'project-update.comment', 'uses' => 'ProjectUpdateController@comment']);
    Route::resource('project-update', 'ProjectUpdateController', [
        'only'=>['edit', 'update', 'destroy', 'store']
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Idea
        Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

        Route::resource('idea', 'IdeaController', [
            'names' => [
                'index' => 'idea',
                'create' => 'idea.create',
                'store' => 'idea.store',
                'show' => 'idea.show',
                'edit' => 'idea.edit',
                'update' => 'idea.update',
                'destroy' => 'idea.destroy'
            ]
        ]);

        //IdeaVote
        Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
        /*
        Route::resource('ideavote', 'IdeaVoteController', [
            'names' => [
                'store' => 'ideavote.store',
                'destroy' => 'ideavote.destroy'
            ]
        ]);
        */
    });

    // Timesheet
    Route::resource('timesheet', 'TimesheetController', [
        'names' => [
            'index' => 'timesheet',
            'store' => 'timesheet.store',
            'show' => 'timesheet.show',
            'edit' => 'timesheet.edit',
            'update' => 'timesheet.update',
            'destroy' => 'timesheet.destroy'
        ]
    ]);

    //File
    Route::resource('file', 'FileController', [
        'names' => [
            'index' => 'file',
            'store' => 'file.store',
            'show' => 'file.show',
            'edit' => 'file.edit',
            'update' => 'file.update',
            'destroy' => 'file.destroy'
        ]
    ]);

    Route::get('create/{ticket?}', ['as' => 'timesheet.create', 'uses' => 'TimesheetController@create']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // User
        Route::resource('user', 'UserController', [
            'names' => [
                'index' => 'user',
                'create' => 'user.create',
                'store' => 'user.store',
                'show' => 'user.show',
                'edit' => 'user.edit',
                'update' => 'user.update',
                'destroy' => 'user.destroy'
            ]
        ]);
    });

    //Notes

    Route::get('note/create/{user}', ['as' => 'note.create', 'uses' => 'NoteController@create']);
    Route::post('note/store/{user}', ['as' => 'note.store', 'uses' => 'NoteController@store']);
    Route::get('note/edit/{note}', ['as' => 'note.edit', 'uses' => 'NoteController@edit']);
    Route::post('note/update/{note}', ['as' => 'note.update', 'uses' => 'NoteController@update']);

app/Models/Project/ProjectInternalStatus.php
<?php

namespace DCODESupport\Models\Project;

use Illuminate\Database\Eloquent\Model;

class ProjectInternalStatus extends Model
{
    //
}

app/Models/Project/ProjectStatus.php
<?php

namespace DCODESupport\Models\Project;

use Illuminate\Database\Eloquent\Model;

class ProjectStatus extends Model
{
    //
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace DCODESupport\Http\Controllers\Admin;

use DCODESupport\Models\Client\Client;
use DCODESupport\Models\Project\Project;
use DCODESupport\Services\Client\ClientService;
use DCODESupport\Services\Project\ProjectService;
use Illuminate\Http\Request;

use DCODESupport\Http\Requests;
use DCODESupport\Http\Requests\Client\ClientRequest;
use DCODESupport\Http\Controllers\Controller;


class ClientController extends Controller
{
    protected $service;

	public function __construct()
	{
		$this->service = new ClientService();
	}

	public function index()
	{
		$clients = $this->service->search();

		return view('admin.client.list')
			->with('clients', $clients);
	}

	public function show(Client $client){
        $projects = ProjectService::search(null, $client);

	    return view('admin.client.show')
            ->with('client', $client)
            ->with('projects', $projects)
            ->with('panel2', '');
    }

	public function create()
	{
		return view('admin.client.edit');
	}

	public function store(ClientRequest $request)
	{
		$this->service->save($request, null);

        //Check if the request is ajax
        if ($request->ajax() || $request->wantsJson()){
            //Ajax request response
            return response()->json('');
        }else{
            return redirect()
                ->route('admin.client')
                ->with('flashNotice', 'Client saved ...');
        }
	}

	public function edit(Client $client)
	{
		return view('admin.client.edit')
			->with('client', $client);
	}

	public function update(ClientRequest $request, Client $client)
	{
		$this->service->save($request, $client);

        //Check if the request is ajax
        if ($request->ajax() || $request->wantsJson()){
            //Ajax request response
            return response()->json('');
        }else{
            return redirect()
                ->route('admin.client')
                ->with('flashNotice', 'Client saved ...');
        }
	}

	public function destroy(Client $client)
	{
		$this->service->delete($client);

		return redirect()
			->route('admin.client')
			->with('flashNotice', 'Client deleted ...');
	}
}

app/Http/Controllers/Admin/ProjectController.php
<?php

namespace DCODESupport\Http\Controllers\Admin;

//use DCODESupport\Http\Requests\Request;
use \Illuminate\Support\Facades\Request;

use DCODESupport\Models\Client\Client;
use DCODESupport\Models\Project\Project;
use DCODESupport\Models\Project\ProjectUser;
use DCODESupport\Services\NavigationService;
use DCODESupport\Services\Project\ProjectService;
use DCODESupport\User;
use DCODESupport\Http\Requests\Project\ProjectRequest;
use DCODESupport\Http\Controllers\Controller;

class ProjectController extends Controller
{
	protected $service;
	
	public function __construct()
	{
		$this->service = new ProjectService();
	}
	
	public function index()
	{
        NavigationService::setPosition('projects');

		$projects = $this->service->search();
		
		return view('admin.project.list')
			->with('projects', $projects);
	}
	
	public function create()
	{
		return view('admin.project.edit');
	}
	
	public function store(ProjectRequest $request)
	{
		$client = Client::find($request->get('client_id'));

		$this->service->save($request, $client, null);

        //Check if the request is ajax
        if ($request->ajax() || $request->wantsJson()){
            //Ajax request response
            return response()->json('');
        }else{
            $defaultRoute = route('admin.project');
            return NavigationService::returnPosition('projects', $defaultRoute, 'Project saved.');
        }
	}

	public function show(Project $project)
	{
        NavigationService::setPosition('projects');

		return view('admin.project.show')
			->with('project', $project);
	}
	
	public function edit(Project $project)
	{
		return view('admin.project.edit')
			->with('project', $project);
	}
	
	public function update(ProjectRequest $request, Project $project)
	{
		$client = $project->client;

		$this->service->save($request, $client, $project);

        //Check if the request is ajax
        if ($request->ajax() || $request->wantsJson()){
            //Ajax request response
            return response()->json('');
        }else{
            $defaultRoute = route('admin.project');
            return NavigationService::returnPosition('projects', $defaultRoute, 'Project saved.');
        }
	}
	
	public function destroy(Project $project)
	{
		$this->service->delete($project);

        $defaultRoute = route('admin.project');

        return NavigationService::returnPosition('projects', $defaultRoute, 'Project deleted.');
	}

	// General ...
	public function access(Project $project)
	{
		$internalUsers = $project->internalUsers();
		$clientUsers = $project->clientUsers();
		$projectUsers = $project->projectUsers();

		return view('admin.project.access')
			->with('project', $project)
			->with('internalUsers', $internalUsers)
			->with('clientUsers', $clientUsers)
			->with('projectUsers', $projectUsers);
	}

	public function cancelAccess(ProjectUser $projectUser)
	{
		$project = $projectUser->project;
		
		$this->service->cancelAccess($projectUser);

		return redirect()
			->route('admin.project.access', $project->id)
			->with('flashNotice', 'User provided access ...');
	}

	public function user(Project $project)
	{
		$user = User::find(\Request::get('userId'));

		$this->service->userAccess($project, $user);

		return redirect()
			->route('admin.project.access', $project->id)
			->with('flashNotice', 'User provided access ...');
	}

    /**
     * The project code to be the short code of the client, the year
     * and then an integer (with 4 digits) of the number of project
     * this is for the client
     *
     * @return string
     */
	public function genProjectCode(){
        if(Request::ajax()){
            //Get client ID
            $clientId = request('clientId');
            //Get project code
            $projectCode = ProjectService::generateProjectCode($clientId);

            return response()->json($projectCode);
        }
    }

    public function add(Client $client)
    {
        return view('admin.project.edit')
            ->with('client', $client);
    }
}

app/Http/Controllers/Client/ClientController.php
<?php

namespace DCODESupport\Http\Controllers\Client;

use Illuminate\Http\Request;

use DCODESupport\Http\Requests;
use DCODESupport\Http\Controllers\Controller;

class ClientController extends Controller
{
	public function index()
	{
		return view('client.dashboard');
	}
}

app/Http/Controllers/Client/TaskController.php
<?php

namespace DCODESupport\Http\Controllers\Client;

use DCODESupport\Services\Ticket\TicketService;
use Illuminate\Http\Request;

use DCODESupport\Http\Requests;
use DCODESupport\Http\Controllers\Controller;

class TaskController extends Controller
{
	protected $service;
	
	public function __construct()
	{
		$this->service = new TicketService();
	}
	
	public function index()
	{
		$pendingTickets = $this->service->search(null, null, '0', \Auth::user());
		$outstandingTickets = $this->service->search(null, null, '1', \Auth::user());
		$completedTickets = $this->service->search(null, null, '2', \Auth::user());
		$approvedTickets = $this->service->search(null, null, '3', \Auth::user());
		
		return view('client.task.list')
			->with('pendingTickets', $pendingTickets)
			->with('outstandingTickets', $outstandingTickets)
			->with('completedTickets', $completedTickets)
			->with('approvedTickets', $approvedTickets);
	}
}

resources/views/client/project/edit.blade.php
@extends('layouts.modal')

@section('header')
	<h1>Add Project</h1>
@stop

@section('content')
	<div class="warnMessage"></div>
	<div class="main form formModal">

			{!! Form::open(['route' => 'client.project.store', 'id'=>'storeProjectForm']) !!}

		<fieldset>
			<div>
				{!! Form::hidden('client_id', \Auth::user()->client_id) !!}
				{!! DisplayService::displayClient(\Auth::user()->client()->first()) !!}
			</div>
			<?php /**
			<div>
				{!! Form::hidden('code','Dummy code') !!}

			</div>
	 		**/ ?>
			<div>
				{!! Form::label('name', 'Project name:') !!}
				{!! Form::text('name') !!}
			</div>
			<div>
				{{-- Assuming active --}}
				{!! Form::hidden('active', '1') !!}
			</div>

		</fieldset>

		<div class="formAction">
			{!! Form::submit('Save', ['class' => 'buttonAction']) !!}
			<a class="buttonClear" href="{{ URL::previous() }}">Cancel</a>
		</div>

		{!! Form::close() !!}
	</div>
@stop

@section('javascript')
	<script type="application/javascript">
			bindErrorAjaxModal('#editModal #storeProjectForm', '{{ route('client.project.store') }}', 'POST');
	</script>
@stop

resources/views/client/project/list.blade.php
@extends('layouts.client')

@section('controlPanelHeader')
	<a class="buttonAction edit" data-href="{{ route('client.project.create') }}"><span>+</span></a>
	<h3>Projects</h3>
@endsection

@section('controlPanelBody')
	{!! Form::open(['route' => 'client.project', 'method' => 'GET', 'id' => 'searchForm']) !!}
	{!! Form::hidden('export', '0') !!}
	{!! Form::hidden('sort', (\Request::get('sort') !== null ? \Request::get('sort') : 'created_at')) !!}
	{!! Form::hidden('sortDir', (\Request::get('sortDir') == 'asc' ? 'asc' : 'desc')) !!}

			<!-- hr / -->

	<div class="options">
		{!! Form::label('sort', 'Sort By') !!}
		{!! Form::select('sort', ['code' => 'Code', 'name' => 'Name', 'client' => 'Client', 'created_at' => 'Created At'], (\Request::get('sort') !== null ? \Request::get('sort') : 'created_at')) !!}
	</div>

	<br />

	<div class="search">
		{!! Form::text('code', \Request::get('code'), ['placeholder' => 'Project Code']) !!}
	</div>
	<div class="search">
		{!! Form::text('name', \Request::get('name'), ['placeholder' => 'Name']) !!}
	</div>
	<div>
		{!! Form::checkbox('active', '0', \Request::get('active')) !!}
		{!! Form::label('active', 'Show Archived Projects') !!}
	</div>

	<div>
		{!! Form::submit('Search', ['class' => 'buttonAction']) !!}
		<a class="buttonClear" href="{{ route('client.project') }}">Clear</a>
	</div>
	{!! Form::close() !!}
@endsection

@section('content')
	<div class="cards">
		@if ($projects->count() > 0)

@foreach ($projects as $project)
				<div class="cardContainer">
					<div class="card">
						<!-- a href="{{ route('client.project.show', $project->id) }}" -->
							<header>
								<h3>{{ $project->name }} {!! ($project->active == '1' ? '<span class="badge success"></span>' : '') !!}</h3>
								<span>{{ $project->code }}</span>
							</header>
							<div class="cardBody">
								<div class="cardBody__item">
									<label>Client</label>
									{{ DisplayService::displayClient($project->client) }}
								</div>

								<div class="cardBody__item">
									<label>Name</label>
									{{ $project->name }}
								</div>

								<div class="cardBody__item">
									<label>Created</label>
									{{ date("d/m/Y", strtotime($project->created_at)) }}
								</div>

								<div class="cardBody__item">
									<label>Added By</label>
									{{ DisplayService::displayUser($project->user) }}
								</div>

								<div class="cardBody__item">
									<label>Next Milestone</label>
									@if ($project->nextMilestone() != null)
										{{ $project->nextMilestone()->name }}
										<span class="label small {{ ($project->nextMilestone()->scheduled < time() ? 'alert' : 'success') }}">{{ DisplayService::displayDate($project->nextMilestone()->scheduled) }}</span>
									@else
										NA
									@endif
								</div>

								<div class="cardBody__item">
									<label>Status</label>
									@if ($project->latestUpdate() != null)
										<span class="{{ $project->latestUpdate()->projectStatus->class }}">{{ DisplayService::displayProjectStatus($project->latestUpdate()->projectStatus) }}</span><br />
										@if ($project->latestUpdate()->comments()->count() > 0)
											<small>{{ DisplayService::displayExcerpt($project->latestUpdate()->comments()->orderBy('created_at', 'asc')->first()->comment) }}</small>
										@endif
									@else
										NA
									@endif
								</div>
							</div>
						</a>
						<footer>
							<a class="button round" href="{{ route('client.ticket', ['project_id' => $project->id]) }}" aria-describedby="ticketCount">Tickets <span class="badge alert" id="ticketCount">{{ $project->activeTickets()->count() }}</span></a>
						</footer>
					</div>
				</div>
			@endforeach

			<div class="cards__pagination">
				{!! $projects->appends(\Request::except('page'))->render() !!}
			</div>
		@else
			<div class="cards__empty">
				<h3>No projects</h3>
				<p>No projects ...</p>
			</div>
		@endif
	</div>
@endsection