routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

if (App::environment('production')) {
    URL::forceSchema('https');
}

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::auth();

Auth::routes();

Route::get('/', ['uses' => 'HomeController@index']);

Route::get('logout', 'Auth\LoginController@logout');

// Account
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Account', 'prefix' => 'account'], function () {
    Route::get('/', ['as' => 'account', 'uses' => 'AccountController@index']);
    Route::post('update', ['as' => 'account.update', 'uses' => 'AccountController@update']);
});

// Client
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Client', 'prefix' => 'client', 'as' => 'client.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'ClientController@index']);

    // Projects
    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'show' => 'project.show'
        ]
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    // Idea
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

    Route::resource('idea', 'IdeaController', [
        'names' => [
            'index' => 'idea',
            'create' => 'idea.create',
            'store' => 'idea.store',
            'show' => 'idea.show',
            'edit' => 'idea.edit',
            'update' => 'idea.update',
            'destroy' => 'idea.destroy'
        ]
    ]);

    //IdeaVote
    Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
});

// Admin
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access', 'internal'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Client
        Route::resource('client', 'ClientController', [
            'names' => [
                'index' => 'client',
                'create' => 'client.create',
                'store' => 'client.store',
                'show' => 'client.show',
                'edit' => 'client.edit',
                'update' => 'client.update',
                'destroy' => 'client.destroy'
            ]
        ]);
    });

    // Projects
    Route::get('project/add/{client}', ['as' => 'project.add', 'uses' => 'ProjectMilestoneController@add']);

    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'create' => 'project.create',
            'store' => 'project.store',
            'show' => 'project.show',
            'edit' => 'project.edit',
            'update' => 'project.update',
            'destroy' => 'project.destroy'
        ]
    ]);
    Route::get('project/access/{project}', ['as' => 'project.access', 'uses' => 'ProjectController@access']);
    Route::post('project/projectcode', ['as' => 'project.projectcode', 'uses' => 'ProjectController@genProjectCode']);
    Route::post('project/user/{project}', ['as' => 'project.user', 'uses' => 'ProjectController@user']);
    Route::delete('project/cancel-access/{project_user}', ['as' => 'project.cancel-access', 'uses' => 'ProjectController@cancelAccess']);

    // Project Milestones
    Route::get('project-milestone/{project}', ['as' => 'project-milestone', 'uses' => 'ProjectMilestoneController@index']);
    Route::get('project-milestone/add/{project}', ['as' => 'project-milestone.add', 'uses' => 'ProjectMilestoneController@add']);
    Route::post('project-milestone/save/{project}', ['as' => 'project-milestone.save', 'uses' => 'ProjectMilestoneController@save']);
    Route::resource('project-milestone', 'ProjectMilestoneController', [
        'names' => [
            'show' => 'project-milestone.show',
            'edit' => 'project-milestone.edit',
            'update' => 'project-milestone.update',
            'destroy' => 'project-milestone.destroy'
        ]
    ]);

    // Project Updates
    Route::get('project-update/{project}', ['as' => 'project-update', 'uses' => 'ProjectUpdateController@index']);
    Route::get('project-update/add/{project}', ['as' => 'project-update.add', 'uses' => 'ProjectUpdateController@add']);
    Route::post('project-update/save/{project}', ['as' => 'project-update.save', 'uses' => 'ProjectUpdateController@save']);
    Route::get('project-update/show/{project_update}', ['as' => 'project-update.show', 'uses' => 'ProjectUpdateController@show']);
    Route::post('project-update/comment/{project_update}', ['as' => 'project-update.comment', 'uses' => 'ProjectUpdateController@comment']);
    Route::resource('project-update', 'ProjectUpdateController', [
        'only'=>['edit', 'update', 'destroy', 'store']
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Idea
        Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

        Route::resource('idea', 'IdeaController', [
            'names' => [
                'index' => 'idea',
                'create' => 'idea.create',
                'store' => 'idea.store',
                'show' => 'idea.show',
                'edit' => 'idea.edit',
                'update' => 'idea.update',
                'destroy' => 'idea.destroy'
            ]
        ]);

        //IdeaVote
        Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
        /*
        Route::resource('ideavote', 'IdeaVoteController', [
            'names' => [
                'store' => 'ideavote.store',
                'destroy' => 'ideavote.destroy'
            ]
        ]);
        */
    });

    // Timesheet
    Route::resource('timesheet', 'TimesheetController', [
        'names' => [
            'index' => 'timesheet',
            'store' => 'timesheet.store',
            'show' => 'timesheet.show',
            'edit' => 'timesheet.edit',
            'update' => 'timesheet.update',
            'destroy' => 'timesheet.destroy'
        ]
    ]);

    //File
    Route::resource('file', 'FileController', [
        'names' => [
            'index' => 'file',
            'store' => 'file.store',
            'show' => 'file.show',
            'edit' => 'file.edit',
            'update' => 'file.update',
            'destroy' => 'file.destroy'
        ]
    ]);

    Route::get('create/{ticket?}', ['as' => 'timesheet.create', 'uses' => 'TimesheetController@create']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // User
        Route::resource('user', 'UserController', [
            'names' => [
                'index' => 'user',
                'create' => 'user.create',
                'store' => 'user.store',
                'show' => 'user.show',
                'edit' => 'user.edit',
                'update' => 'user.update',
                'destroy' => 'user.destroy'
            ]
        ]);
    });

    //Notes

    Route::get('note/create/{user}', ['as' => 'note.create', 'uses' => 'NoteController@create']);
    Route::post('note/store/{user}', ['as' => 'note.store', 'uses' => 'NoteController@store']);
    Route::get('note/edit/{note}', ['as' => 'note.edit', 'uses' => 'NoteController@edit']);
    Route::post('note/update/{note}', ['as' => 'note.update', 'uses' => 'NoteController@update']);

app/Http/Controllers/Admin/TaskController.php
<?php

namespace DCODESupport\Http\Controllers\Admin;

use DCODESupport\Services\Ticket\TicketService;
use Illuminate\Http\Request;

use DCODESupport\Http\Requests;
use DCODESupport\Http\Controllers\Controller;

class TaskController extends Controller
{
	
	protected $service;
	
	public function __construct()
	{
		$this->service = new TicketService();
	}
	
	public function index()
	{
		
		$pendingTickets = $this->service->search(null, null, '0');
		//dd($pendingTickets);
		//dd(\DB::getQueryLog());
		//\DB::enableQueryLog();
		$outstandingTickets = $this->service->search(null, null, '1');
		//	dd($outstandingTickets);
		$completedTickets = $this->service->search(null, null, '2');
		//	dd($completedTickets);
		$approvedTickets = $this->service->search(null, null, '3');
		// dd($approvedTickets);
		
		$projects      = TicketService::projects();
		$assignedUsers = TicketService::users();
		
		return view('admin.task.list')
			->with('projects', $projects)
			->with('assignedUsers', $assignedUsers)
			->with('pendingTickets', $pendingTickets)
			->with('outstandingTickets', $outstandingTickets)
			->with('completedTickets', $completedTickets)
			->with('approvedTickets', $approvedTickets);
	}
}

app/Http/Controllers/Client/TaskController.php
<?php

namespace DCODESupport\Http\Controllers\Client;

use DCODESupport\Services\Ticket\TicketService;
use Illuminate\Http\Request;

use DCODESupport\Http\Requests;
use DCODESupport\Http\Controllers\Controller;

class TaskController extends Controller
{
	protected $service;
	
	public function __construct()
	{
		$this->service = new TicketService();
	}
	
	public function index()
	{
		$pendingTickets = $this->service->search(null, null, '0', \Auth::user());
		$outstandingTickets = $this->service->search(null, null, '1', \Auth::user());
		$completedTickets = $this->service->search(null, null, '2', \Auth::user());
		$approvedTickets = $this->service->search(null, null, '3', \Auth::user());
		
		return view('client.task.list')
			->with('pendingTickets', $pendingTickets)
			->with('outstandingTickets', $outstandingTickets)
			->with('completedTickets', $completedTickets)
			->with('approvedTickets', $approvedTickets);
	}
}

resources/views/admin/task/list.blade.php
@extends('layouts.admin')

@section('controlPanelHeader')
	<a class="buttonAction edit" href="{{ route('admin.ticket.create') }}"><span>+</span></a>
	<h3>Tasks</h3>
@endsection

@section('controlPanelBody')

{!! Form::open(['route' => 'admin.task', 'method' => 'GET', 'id' => 'searchForm']) !!}
	{!! Form::hidden('export', '0') !!}
	{!! Form::hidden('sort', (\Request::get('sort') !== null ? \Request::get('sort') : 'created_at')) !!}
	{!! Form::hidden('sortDir', (\Request::get('sortDir') == 'asc' ? 'asc' : 'desc')) !!}

	<!-- hr / -->

	<div class="options">
		{!! Form::label('client_id', 'Client') !!}
		{!! Form::clientSelect('client_id', \Request::get('client_id')) !!}
	</div>
	<hr />

	<div class="options">
		{!! Form::label('project_id', 'Project') !!}
		{!! Form::projectSelect('project_id', \Request::get('project_id')) !!}
	</div>
	<hr />

	<div class="options">
		{!! Form::label('assigned_user_id', 'Assigned To') !!}
		{!! Form::assignedUserSelect('assigned_user_id', \Request::get('assigned_user_id')) !!}
	</div>
	<hr />

	<div class="search">
		{!! Form::text('name', \Request::get('name'), ['placeholder' => 'Task Name']) !!}
	</div>
	<br/>

	<div>
		{!! Form::submit('Search', ['class' => 'buttonAction']) !!}
		<a class="buttonClear" href="{{ route('client.project') }}">Clear</a>
	</div>
{!! Form::close() !!}
@endsection

@section('content')
	<script>
		$(function() {
			$( ".taskBoard__column" ).sortable({
				connectWith: ".taskBoard__column",
				handle: ".taskBoard__ticket--container",
				cancel: ".portlet-toggle",
				placeholder: "portlet-placeholder ui-corner-all",

				receive: function( event, ui ) {
					var ticketId = ui.item.context.id;
					var statusId = event.target.id;

					$.ajax({
						type: "POST",
						url : "/admin/ticket/status",
						data: { ticketId: ticketId, statusId: statusId },
						success : function(data){
						    var pending = $('.taskBoard__column.pending.ui-sortable .taskBoard__ticket').length;
						    var outstanding = $('.taskBoard__column.outstanding.ui-sortable .taskBoard__ticket').length;
						    var completed = $('.taskBoard__column.completed.ui-sortable .taskBoard__ticket').length;
						    var approved = $('.taskBoard__column.approved.ui-sortable .taskBoard__ticket').length;

						    //Change count pending
							$('.taskBoard__header--column.pending').html('Pending' + ' ' + pending);
							//Change count outstanding
                            $('.taskBoard__header--column.outstanding').html('Outstanding' + ' ' + outstanding);
							//Change count completed
                            $('.taskBoard__header--column.completed').html('Completed' + ' ' + completed);
							//Change count approved
                            $('.taskBoard__header--column.approved').html('Approved' + ' ' + approved);

							$('#notice .message').html('Saved ...');
							$('#notice').slideDown();
							setTimeout(function(){
								$('#notice').slideUp();
							}, 2000);
						},
						async:true
					});
				}
			});

			$( ".portlet" )
					.addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
					.find( ".portlet-header" )
					.addClass( "ui-widget-header ui-corner-all" )
					.prepend( "<span class='ui-icon ui-icon-minusthick portlet-toggle'></span>");

			$( ".portlet-toggle" ).click(function() {
				var icon = $( this );
				icon.toggleClass( "ui-icon-minusthick ui-icon-plusthick" );
				icon.closest( ".portlet" ).find( ".portlet-content" ).toggle();
			});
		});
	</script>

	<div class="row" style="width:100%;max-width:100%;">
		<div class="large-12 columns">
			<div class="columns">
				<div class="taskBoard__header">
					<div class="taskBoard__header--column pending">Pending {{ $pendingTickets->count() }}</div>
					<div class="taskBoard__header--column outstanding">Outstanding {{ $outstandingTickets->count() }}</div>
					<div class="taskBoard__header--column completed">Completed {{ $completedTickets->count() }}</div>
					<div class="taskBoard__header--column approved">Approved {{ $approvedTickets->count() }}</div>
				</div>

				<div class="taskBoard">
					<div class="taskBoard__column pending" id="0">
						@foreach ($pendingTickets as $ticket)
							@include('_partials.task.card', ['ticket' => $ticket])
						@endforeach

					</div>

					<div class="taskBoard__column outstanding" id="{{ \DCODESupport\Models\Status::where('name', 'Outstanding')->first()->id }}">
						@foreach ($outstandingTickets as $ticket)
							@include('_partials.task.card', ['ticket' => $ticket])
						@endforeach

					</div>

					<div class="taskBoard__column completed" id="{{ \DCODESupport\Models\Status::where('name', 'Completed')->first()->id }}">
						@foreach ($completedTickets as $ticket)
							@include('_partials.task.card', ['ticket' => $ticket])
						@endforeach

					</div>

					<div class="taskBoard__column approved" id="{{ \DCODESupport\Models\Status::where('name', 'Approved')->first()->id }}">
						@foreach ($approvedTickets as $ticket)
							@include('_partials.task.card', ['ticket' => $ticket])
						@endforeach

					</div>
				</div>
			</div>
		</div>
	</div>


@endsection

@section('javascript')
	<script>
		var $modal = $('#ticketModal');

		$(document).on('click', '.taskBoard__ticket', function(e){
			e.preventDefault();

			$.ajax({
				type: "GET",
				url : '{{ route('admin.ticket.preview') }}?ticketId='+$(this).attr('id'),
				success : function(data){
					$modal.html(data).foundation('open');
				},
				async:true
			});
		});
	</script>

	<script type="text/javascript" >

        function toSeconds(s) {
            var p = s.split(':');
            return parseInt(p[0], 10) * 3600 + parseInt(p[1], 10) * 60 + parseInt(p[2], 10);
        }

        function fill(s, digits) {
            s = s.toString();
            while (s.length < digits) s = '0' + s;
            return s;
        }

        Date.prototype.days=function(to){

            return  Math.round(Math.abs((this.getTime() - to.getTime())/(24*60*60*1000)))

        }
        function secondsToHMS(secs) {
            function z(n){return (n<10?'0':'') + n;}
            var sign = secs < 0? '-':'';
            secs = Math.abs(secs);
            return sign + z(secs/3600 |0) + ':' + z((secs%3600) / 60 |0) + ':' + z(secs%60);
        }

        function hmsToSeconds(s) {
            var b = s.split(':');
            return b[0]*3600 + b[1]*60 + (+b[2] || 0);
        }


        function update(){
            $(".elapsed").each(function() {

                var convertTime = new Date($(this).attr('data-val'));
				var currentdate = new Date();

				//console.log("start Time",$(this).attr('data-val'));
                //console.log("now time",currentdate);

                    var daysdiff = new Date(convertTime).days(new Date(currentdate));
                    if(daysdiff==0){
                        var nowTime=currentdate.getHours()+":"+currentdate.getMinutes()+":"+currentdate.getSeconds();
                        var startTime=convertTime.getHours()+":"+convertTime.getMinutes()+":"+convertTime.getSeconds();
                        var countDown= secondsToHMS(hmsToSeconds(nowTime) - hmsToSeconds(startTime));
                    }
                    else{
                        var nowTime=24*daysdiff+currentdate.getHours()+":"+currentdate.getMinutes()+":"+currentdate.getSeconds();
                        var startTime=convertTime.getHours()+":"+convertTime.getMinutes()+":"+convertTime.getSeconds();
                        var countDown= secondsToHMS(hmsToSeconds(nowTime) - hmsToSeconds(startTime));
                    }

                    $(this).html(countDown);

				$(".elapsed").css({
                    "display": "inline-block",
                    }).delay(100).animate({
					"background-color": "##6ab63c",
                    "display": "inline-block",
                    "border-radius": "5px"}, 1500, function () {
                    $(".elapsed").animate({
                        "background-color": "#fff",
                    },0.1);
                })
            });
            window.setTimeout("update()", 1000);

		}
		update();


	</script>
@stop