routes/web.php
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

if (App::environment('production')) {
    URL::forceSchema('https');
}

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
//Route::auth();

Auth::routes();

Route::get('/', ['uses' => 'HomeController@index']);

Route::get('logout', 'Auth\LoginController@logout');

// Account
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Account', 'prefix' => 'account'], function () {
    Route::get('/', ['as' => 'account', 'uses' => 'AccountController@index']);
    Route::post('update', ['as' => 'account.update', 'uses' => 'AccountController@update']);
});

// Client
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access'], 'namespace' => 'Client', 'prefix' => 'client', 'as' => 'client.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'ClientController@index']);

    // Projects
    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'show' => 'project.show'
        ]
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    // Idea
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

    Route::resource('idea', 'IdeaController', [
        'names' => [
            'index' => 'idea',
            'create' => 'idea.create',
            'store' => 'idea.store',
            'show' => 'idea.show',
            'edit' => 'idea.edit',
            'update' => 'idea.update',
            'destroy' => 'idea.destroy'
        ]
    ]);

    //IdeaVote
    Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
});

// Admin
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['access', 'internal'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Client
        Route::resource('client', 'ClientController', [
            'names' => [
                'index' => 'client',
                'create' => 'client.create',
                'store' => 'client.store',
                'show' => 'client.show',
                'edit' => 'client.edit',
                'update' => 'client.update',
                'destroy' => 'client.destroy'
            ]
        ]);
    });

    // Projects
    Route::get('project/add/{client}', ['as' => 'project.add', 'uses' => 'ProjectMilestoneController@add']);

    Route::resource('project', 'ProjectController', [
        'names' => [
            'index' => 'project',
            'create' => 'project.create',
            'store' => 'project.store',
            'show' => 'project.show',
            'edit' => 'project.edit',
            'update' => 'project.update',
            'destroy' => 'project.destroy'
        ]
    ]);
    Route::get('project/access/{project}', ['as' => 'project.access', 'uses' => 'ProjectController@access']);
    Route::post('project/projectcode', ['as' => 'project.projectcode', 'uses' => 'ProjectController@genProjectCode']);
    Route::post('project/user/{project}', ['as' => 'project.user', 'uses' => 'ProjectController@user']);
    Route::delete('project/cancel-access/{project_user}', ['as' => 'project.cancel-access', 'uses' => 'ProjectController@cancelAccess']);

    // Project Milestones
    Route::get('project-milestone/{project}', ['as' => 'project-milestone', 'uses' => 'ProjectMilestoneController@index']);
    Route::get('project-milestone/add/{project}', ['as' => 'project-milestone.add', 'uses' => 'ProjectMilestoneController@add']);
    Route::post('project-milestone/save/{project}', ['as' => 'project-milestone.save', 'uses' => 'ProjectMilestoneController@save']);
    Route::resource('project-milestone', 'ProjectMilestoneController', [
        'names' => [
            'show' => 'project-milestone.show',
            'edit' => 'project-milestone.edit',
            'update' => 'project-milestone.update',
            'destroy' => 'project-milestone.destroy'
        ]
    ]);

    // Project Updates
    Route::get('project-update/{project}', ['as' => 'project-update', 'uses' => 'ProjectUpdateController@index']);
    Route::get('project-update/add/{project}', ['as' => 'project-update.add', 'uses' => 'ProjectUpdateController@add']);
    Route::post('project-update/save/{project}', ['as' => 'project-update.save', 'uses' => 'ProjectUpdateController@save']);
    Route::get('project-update/show/{project_update}', ['as' => 'project-update.show', 'uses' => 'ProjectUpdateController@show']);
    Route::post('project-update/comment/{project_update}', ['as' => 'project-update.comment', 'uses' => 'ProjectUpdateController@comment']);
    Route::resource('project-update', 'ProjectUpdateController', [
        'only'=>['edit', 'update', 'destroy', 'store']
    ]);

    // Task
    Route::group(['prefix' => 'task'], function () {
        Route::get('/', ['as' => 'task', 'uses' => 'TaskController@index']);
    });

    // Ticket
    Route::post('ticket/comment/{ticket}', ['as' => 'ticket.comment', 'uses' => 'TicketController@comment']);
    Route::get('ticket/preview', ['as' => 'ticket.preview', 'uses' => 'TicketController@preview']);
    Route::post('ticket/status', ['as' => 'ticket.status', 'uses' => 'TicketController@status']);

    Route::resource('ticket', 'TicketController', [
        'names' => [
            'index' => 'ticket',
            'create' => 'ticket.create',
            'store' => 'ticket.store',
            'show' => 'ticket.show',
            'edit' => 'ticket.edit',
            'update' => 'ticket.update',
            'destroy' => 'ticket.destroy'
        ]
    ]);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // Idea
        Route::post('idea/comment/{idea}', ['as' => 'idea.comment', 'uses' => 'IdeaController@comment']);

        Route::resource('idea', 'IdeaController', [
            'names' => [
                'index' => 'idea',
                'create' => 'idea.create',
                'store' => 'idea.store',
                'show' => 'idea.show',
                'edit' => 'idea.edit',
                'update' => 'idea.update',
                'destroy' => 'idea.destroy'
            ]
        ]);

        //IdeaVote
        Route::post('ideavote', 'IdeaVoteController@vote')->name('ideavote.vote');
        /*
        Route::resource('ideavote', 'IdeaVoteController', [
            'names' => [
                'store' => 'ideavote.store',
                'destroy' => 'ideavote.destroy'
            ]
        ]);
        */
    });

    // Timesheet
    Route::resource('timesheet', 'TimesheetController', [
        'names' => [
            'index' => 'timesheet',
            'store' => 'timesheet.store',
            'show' => 'timesheet.show',
            'edit' => 'timesheet.edit',
            'update' => 'timesheet.update',
            'destroy' => 'timesheet.destroy'
        ]
    ]);

    //File
    Route::resource('file', 'FileController', [
        'names' => [
            'index' => 'file',
            'store' => 'file.store',
            'show' => 'file.show',
            'edit' => 'file.edit',
            'update' => 'file.update',
            'destroy' => 'file.destroy'
        ]
    ]);

    Route::get('create/{ticket?}', ['as' => 'timesheet.create', 'uses' => 'TimesheetController@create']);

    Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin']], function () {
        // User
        Route::resource('user', 'UserController', [
            'names' => [
                'index' => 'user',
                'create' => 'user.create',
                'store' => 'user.store',
                'show' => 'user.show',
                'edit' => 'user.edit',
                'update' => 'user.update',
                'destroy' => 'user.destroy'
            ]
        ]);
    });

    //Notes

    Route::get('note/create/{user}', ['as' => 'note.create', 'uses' => 'NoteController@create']);
    Route::post('note/store/{user}', ['as' => 'note.store', 'uses' => 'NoteController@store']);
    Route::get('note/edit/{note}', ['as' => 'note.edit', 'uses' => 'NoteController@edit']);
    Route::post('note/update/{note}', ['as' => 'note.update', 'uses' => 'NoteController@update']);
    Route::get('note/{user}', ['as' => 'note', 'uses' => 'NoteController@index']);
    Route::resource('note', 'NoteController', [
        'only'=>['destroy']
    ]);
});

//Webhook
Route::group(['prefix' => 'webhook', 'as' => 'webhook.'], function () {

app/User.php
<?php

namespace DCODESupport;

use DCODESupport\Models\Project\Project;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // Belongs to ...
    public function client()
    {
        return $this->belongsTo('DCODESupport\Models\Client\Client');
    }

    // Has many ...
    public function projectUsers()
    {
        return $this->hasMany('DCODESupport\Models\Project\ProjectUser', 'access_user_id', 'id');
    }

    public function projects()
    {
        return $this->hasMany('DCODESupport\Models\Project\Project', 'user_id', 'id');
    }

    public function notes()
    {
        return $this->hasMany('DCODESupport\Models\Note\Note', 'user_id', 'id');
    }


    // General ...
    public function access(Project $project)
    {
        if ($this->projectUsers()->where('project_id', $project->id)->count() > 0)
        {
            return true;
        }

        return false;
    }

    public function hasRole($roles)
    {
        if(is_array($roles))
        {
			foreach($roles as $need_role)
            {
                if($this->{$need_role} != '1') {
                    return false;
                }
            }
            return true;
		} else{
            return ($this->{$need_role} == '1' ? true : false);
        }

		return false;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace DCODESupport\Http\Controllers\Admin;

use DCODESupport\Services\User\UserService;
use DCODESupport\User;
use Illuminate\Http\Request;

use DCODESupport\Http\Requests;
use DCODESupport\Http\Requests\User\UserRequest;
use DCODESupport\Http\Controllers\Controller;

class UserController extends Controller
{
    protected $service;

	public function __construct()
	{
		$this->service = new UserService();
	}

	public function index()
	{
		$users = $this->service->search();

		return view('admin.user.list')
			->with('users', $users);
	}

	public function create()
	{
		return view('admin.user.edit');
	}

	public function store(UserRequest $request)
	{
		$this->service->save($request, null);

        //Check if the request is ajax
        if ($request->ajax() || $request->wantsJson()){
            //Ajax request response
            return response()->json('');
        }else{
            return redirect()
                ->route('admin.user')
                ->with('flashNotice', 'User saved ...');
        }
	}

	public function edit(User $user)
	{
		return view('admin.user.edit')
			->with('user', $user);
	}

	public function update(UserRequest $request, User $user)
	{
		$this->service->save($request, $user);

        //Check if the request is ajax
        if ($request->ajax() || $request->wantsJson()){
            //Ajax request response
            return response()->json('');
        }else{
            return redirect()
                ->route('admin.user')
                ->with('flashNotice', 'User saved ...');
        }
	}

	public function destroy(User $user)
	{
		$this->service->delete($user);

		return redirect()
			->route('admin.user')
			->with('flashNotice', 'User deleted ...');
	}
}

resources/views/admin/user/edit.blade.php
@extends('layouts.modal')

@section('header')
    <h1>Add/Edit User</h1>
@stop

@section('content')
    <div class="warnMessage"></div>
    <div class="main form formModal">
        @if (isset($user))
            {!! Form::model($user, ['route' => ['admin.user.update', $user->id], 'method' => 'put', 'id' => 'updateUserForm']) !!}
        @else
            {!! Form::open(['route' => 'admin.user.store', 'id' => 'storeUserForm']) !!}
        @endif

        <fieldset>
            <legend>User</legend>

            <div class="row">
                <div class="large-6 columns">
                    {!! Form::label('first_name', 'First name:') !!}
                    {!! Form::text('first_name') !!}
                </div>

                <div class="large-6 columns">
                    {!! Form::label('last_name', 'Last name:') !!}
                    {!! Form::text('last_name') !!}
                </div>
            </div>

            <div>
                {!! Form::label('email', 'Email:') !!}
                {!! Form::text('email') !!}
            </div>

            <div>
                {!! Form::label('password', 'Password:') !!}
                {!! Form::password('password') !!}
            </div>

            <div>
                {!! Form::label('client_id', 'Client:') !!}
                {!! Form::clientSelect('client_id', (isset($user) ? $user->client_id : null)) !!}
            </div>
        </fieldset>

        <fieldset>
            <legend>Contact Information</legend>

            <div>
                    {!! Form::label('position', 'Position:') !!}
                    {!! Form::text('position') !!}
            </div>

            <div>
                {!! Form::label('location', 'Location:') !!}
                {!! Form::text('location') !!}
            </div>

            <div>
                {!! Form::label('phone', 'Phone:') !!}
                {!! Form::text('phone') !!}
            </div>
        </fieldset>

        <fieldset>
            <legend>Permissions</legend>

            <div class="row">
                <div class="large-4 columns">
                    {!! Form::hidden('internal', 0) !!}
                    {!! Form::checkbox('internal') !!}
                    {!! Form::label('internal', 'Internal to DCODE') !!}
                </div>

                <div class="large-4 columns">
                    {!! Form::hidden('access', 0) !!}
                    {!! Form::checkbox('access') !!}
                    {!! Form::label('access', 'Access') !!}
                </div>

                <div class="large-4 columns">
                    {!! Form::hidden('manager', 0) !!}
                    {!! Form::checkbox('manager') !!}
                    {!! Form::label('manager', 'Manager') !!}
                </div>

                <div class="large-4 columns">
                    {!! Form::hidden('admin', 0) !!}
                    {!! Form::checkbox('admin') !!}
                    {!! Form::label('admin', 'Admin') !!}
                </div>
            </div>
        </fieldset>

        <div class="formAction">
            {!! Form::submit('Save', ['class' => 'buttonAction']) !!}
            <a class="buttonClear" href="{{ URL::previous() }}">Cancel</a>
        </div>

        {!! Form::close() !!}
    </div>
@stop

@section('javascript')
    <script type="application/javascript">
        @if (isset($user))
            bindErrorAjaxModal('#editModal #updateUserForm', '{{ route('admin.user.update', ['id'=>$user->id]) }}', 'POST');
        @else
            bindErrorAjaxModal('#editModal #storeUserForm', '{{ route('admin.user.store') }}', 'POST');
        @endif
    </script>
@stop

resources/views/admin/user/list.blade.php
@extends('layouts.admin')

@section('controlPanelHeader')
    <a class="buttonAction edit" href="{{ route('admin.user.create') }}"><span>+</span></a>
    <h3>Users</h3>
@endsection

@section('controlPanelBody')
    {!! Form::open(['route' => 'admin.user', 'method' => 'GET', 'id' => 'searchForm']) !!}
    {!! Form::hidden('export', '0') !!}
    {!! Form::hidden('sort', (\Request::get('sort') !== null ? \Request::get('sort') : 'created_at')) !!}
    {!! Form::hidden('sortDir', (\Request::get('sortDir') == 'asc' ? 'asc' : 'desc')) !!}

    <div class="search">
        {!! Form::text('name', \Request::get('name'), ['placeholder' => 'User Name']) !!}
    </div>
    <br/>

    <div>
        {!! Form::submit('Search', ['class' => 'buttonAction']) !!}
        <a class="buttonClear" href="{{ route('admin.user') }}">Clear</a>
    </div>
    {!! Form::close() !!}
@endsection

@section('content')
    <div class="admin__table">
        @if ($users->count() > 0)
            <table>
                <thead>
                <?php
                $columns = array(
                    array(
                        'id' => 'last_name',
                        'value' => 'Name',
                        'sort' => true,
                        'width' => '300'
                    ),
                    array(
                        'id' => 'company',
                        'value' => 'Company',
                        'sort' => true,
                        'width' => '200'
                    ),
                    array(
                        'id' => 'position',
                        'value' => 'Position',
                        'sort' => true,
                        'width' => '200'
                    ),
                    array(
                        'id' => 'location',
                        'value' => 'Location',
                        'sort' => true,
                        'width' => '200'
                    ),
                    array(
                        'id' => 'phone',
                        'value' => 'Phone',
                        'sort' => true,
                        'width' => '200'
                    ),
                    array(
                        'id' => 'internal',
                        'value' => 'Internal',
                        'sort' => true,
                        'width' => '100'
                    ),
                    array(
                        'id' => 'access',
                        'value' => 'Access',
                        'sort' => true,
                        'width' => '100'
                    ),
                    array(
                        'id' => 'manager',
                        'value' => 'Manager',
                        'sort' => true,
                        'width' => '100'
                    ),
                    array(
                        'id' => 'admin',
                        'value' => 'Admin',
                        'sort' => true,
                        'width' => '100'
                    ),
                    array(
                        'id' => 'created_at',
                        'value' => 'Created',
                        'sort' => true,
                        'width' => '100'
                    )
                );
                ?>

                @include('_partials.layout.tableHeader', ['columns' => $columns, 'action' => 2])
                </thead>

                <tbody>
                @foreach ($users as $user)
                    <tr>
                        <td><a href="{{ route('admin.note', $user->id) }}">{{ DisplayService::displayUser($user) }}</a></td>
                        <td>{{ DisplayService::displayClient($user->client()->first()) }}</td>
                        <td>{{ $user->position }}</td>
                        <td>{{ $user->location }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>{{ DisplayService::displayCheckbox($user->internal) }}</td>
                        <td>{{ DisplayService::displayCheckbox($user->access) }}</td>
                        <td>{{ DisplayService::displayCheckbox($user->manager) }}</td>
                        <td>{{ DisplayService::displayCheckbox($user->admin) }}</td>
                        <td>{{ date("d/m/Y", strtotime($user->created_at)) }}</td>
                        <td class="alignCenter"><a class="edit" href="{{ route('admin.user.edit', $user->id) }}"><span
                                        class="dicon-edit"></span></a></td>
                        <td class="alignCenter">{!! \Html::delete('admin.user.destroy', $user->id, '<span class="dicon-delete"></span>') !!}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="admin__table--pagination">
                {!! $users->appends(\Request::except('page'))->render() !!}
            </div>
        @else
            <div class="admin__table--empty">
                <h3>No users</h3>
                <p>No users ...</p>
            </div>
        @endif
    </div>
@endsection